

############################################
###   JRWPS_POST: Regional Wave Sys      ###
###      LSF card for development        ###
############################################
#
# LSF options
#
#PBS -N JRWPS_POST
#PBS -j oe
#PBS -S /bin/bash
#PBS -q dev
#PBS -A GLWU-DEV
#PBS -l walltime=08:00:00
##PBS -l select=3:ncpus=104:mem=10GB
#PBS -l select=3:ncpus=120
#PBS -l place=excl
#PBS -l debug=true
#PBS -V
#PBS -o JRWPS_POST.out
#PBS -e JRWPS_POST.out

cd $PBS_O_WORKDIR
 
# Setup the modules
source ../../versions/run.ver
module purge
module load envvar/${envvar_ver}
module load prod_envir/${prod_envir_ver}
module load prod_util/${prod_util_ver}
module load PrgEnv-intel/${PrgEnv_intel_ver}
module load craype/${craype_ver}
module load cray-mpich/${cray_mpich_ver}
module load cray-pals/${cray_pals_ver}
module load intel/${intel_ver}
module load cfp/${cfp_ver}
module load wgrib2/${wgrib2_ver}
module load grib_util/${grib_util_ver}
module load libjpeg/${libjpeg_ver}
module load hdf5/${hdf5_ver}
module load netcdf/${netcdf_ver}
module list

# Set LSF variables
export KMP_AFFINITY=disabled
# specify X threads if using openmp
export OMP_NUM_THREADS=1

ulimit -s unlimited

export IOBUF_PARAMS='*:count=4:size=32M:prefetch=1:preflush=1'

# Set global variables
export modID=rwps
export MODID=RWPS

export HOMErwps=$(cd "$(pwd)/../.." && pwd -P)

runuser=$USER
NWROOT=/lfs/h2/emc/couple/noscrub/${runuser}      # root of file system

# envir now set by version card
# Check HOST file for where to run
. ./HOST_${modID}

# Set pref to point to matching CRAY machines
pref=$( echo $COMROOTp1 | cut -c7 )
export WCOSS_SYSTEM=$( echo $COMROOTp1 | cut -c7 )d1
export WCOSS_SYSTEM_COM=$( echo $COMROOTp1 | cut -c7-9)



export job=JRWPS_POST
export SMSBIN=/gpfs/${pref}p1/emc/globaldump/sms_fake
# Set PDY and cycle here
export COMDATE=`pwd`

echo $COMDATE
ls $COMDATE

if [ -f $COMDATE/PDY_${modID} ]
then
   source $COMDATE/PDY_${modID}
else
  echo '##################################################'
  echo '### ERROR !! : COULD NOT SET THE PDY AND CYCLE ###'
  echo '##################################################'
  exit 1
fi

# Set paths to home etc
export NET=rwps
export RUN=rwps
export model_ver=${rwps_ver}


# Set j-job parameters (extracted from j-job for DEV by new NCO standards)
# the stmp file system is hugely slow
export DATA=/lfs/h2/emc/ptmp/${runuser}/${NET}/${model_ver}/${job}
rm -rf $DATA
mkdir -p $DATA
export jlogfile=/dev/null
export SENDECF=NO 
export SENDDBN=NO
export SENDCOM=YES 

# Set COM paths
export COMINwave=/lfs/h2/emc/couple/noscrub/${runuser}/${RWPSdir}/com/${NET}/${model_ver}
export COMIN=/lfs/h2/emc/couple/noscrub/${runuser}/${RWPSdir}/com/${NET}/${model_ver}/${RUN}.${PDY}

export COMOUTwave=/lfs/h2/emc/couple/noscrub/${runuser}/${RWPSdir}/com/${NET}/${model_ver}
export COMOUT=/lfs/h2/emc/couple/noscrub/${runuser}/${RWPSdir}/com/${NET}/${model_ver}/${RUN}.${PDY}
export COMINOUT=$COMOUT

export COMROOT=/lfs/h2/emc/couple/noscrub/${runuser}/${RWPSdir}/com/${NET}/${model_ver}


# Choose to keep temporary directory
export KEEPDATA='YES'

export ntask=64

# Execute the actual J job
############################################################################
${HOMErwps}/jobs/J${MODID}_POST
############################################################################
